language: ruby

rvm:
  - 2.3.3

bundler_args: --jobs=2

cache: bundler

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rspec --color --format documentation --require spec_helper --require rails_helper
